FROM python:3.13-slim

WORKDIR /app

COPY requirements.serving.txt .
RUN pip install --no-cache-dir -r requirements.serving.txt

COPY LAIA_Project/ .

# Expose FastAPI port
EXPOSE 8000

# Start App
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]