{
 "title": "Taxi NYC Model Monitoring Dashboard",
 "tags": [
  "mlops",
  "serving"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Avg Latency (s)"
    }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "Req/sec" }
   ]
  },
  {
   "title": "Model Output Distribution",
   "type": "heatmap",
   "description": "Visualizes the distribution of model output. Heavy Distibution shift may signal a heavy behavior change.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(model_prediction_minutes_bucket[5m])) by (le)"
    }
   ]
  },
  {
   "title": "Input Data Drift (Distance Feature)",
   "type": "timeseries",
   "description": "Tracks the average distance in incoming requests. A spike may indicate the input data is drifting from the training set.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(input_feature_distance_sum[5m]) / rate(input_feature_distance_count[5m])",
     "legendFormat": "Avg Input Distance"
    }
   ]
  }
 ]
}