FROM python:3.13-slim

WORKDIR /app

COPY requirements.serving.txt .
RUN pip install --no-cache-dir -r requirements.serving.txt

COPY ./ .

# Expose FastAPI port
EXPOSE 9001

# Start App
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "9001"]